# Generated by Django 5.2.8 on 2025-11-15 06:32

import django.db.models.deletion
import movie_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('poster', models.ImageField(upload_to='posters/', validators=[movie_app.models.validate_file_size])),
                ('video_file', models.FileField(upload_to='videos/', validators=[movie_app.models.validate_file_size])),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('director', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=0.0, help_text='Rating from 0.0 to 10.0')),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movie_app.genre')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('poster', models.ImageField(upload_to='series_posters/', validators=[movie_app.models.validate_file_size])),
                ('genres', models.ManyToManyField(blank=True, related_name='series', to='movie_app.genre')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-start_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, help_text='Optional season title', max_length=200)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='season_posters/', validators=[movie_app.models.validate_file_size])),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie_app.series')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('series', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='episodes/', validators=[movie_app.models.validate_file_size])),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie_app.season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
