# Generated by Django 5.2.8 on 2025-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='view_count',
            new_name='download_count',
        ),
        migrations.AddField(
            model_name='episode',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='file_format',
            field=models.CharField(default='MP4', max_length=10),
        ),
        migrations.AddField(
            model_name='episode',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='episode',
            name='quality',
            field=models.CharField(default='1080p', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='file_format',
            field=models.CharField(default='MP4', help_text='e.g., MP4, MKV', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='file_size',
            field=models.CharField(blank=True, help_text='e.g., 1.5 GB', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(default='1080p', help_text='e.g., 720p, 1080p, 4K', max_length=10),
        ),
    ]
