# Generated by Django 5.2.8 on 2025-11-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_episode_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
    ]
